"""Revision R4: does b recover beta* when beta* is generated by a functional form
DISJOINT from b's linear aggregation?  (Reviewer concern 3, ideal test.)

b is a weighted SUM of proxies. We regenerate beta* as:
  - linear         (baseline; additive logit — matches b's form)
  - multiplicative (Cobb-Douglas-like PRODUCT of drivers)
  - min            (Leontief-like: bottlenecked by the weakest driver)
and report convergent corr(b, beta*), discriminant corr(b, s), AUC, isolation.
If b still recovers beta* under multiplicative/min forms, convergent validity is
not an artifact of shared linear structure.
"""
import numpy as np
import pandas as pd
from pathlib import Path
import copy
import screening as sc

ROOT = Path(__file__).resolve().parents[1]
TAB = ROOT / "results" / "tables"


def run(cfg, scenario, form, n_rep=100):
    cb, cs, auc, iso = [], [], [], []
    for r in range(n_rep):
        c = copy.deepcopy(cfg)
        c["beta_form"] = form
        for k in ["structure", "beta", "noise", "asset", "behavior"]:
            c["seeds"][k] = cfg["seeds"][k] + r
        _, m, _ = sc.run_scenario(c, scenario)
        cb.append(m["corr_b_beta"]); cs.append(m["corr_b_s"])
        auc.append(m["auc"]); iso.append(m["extreme_isolated"])
    return np.mean(cb), np.mean(cs), np.mean(auc), np.mean(iso)


def main():
    cfg = sc.load_config(ROOT / "config.yaml")
    n_rep = cfg["seeds"]["n_replications"]
    rows = []
    for form in ["linear", "multiplicative", "min"]:
        for scen in ["oligopolistic", "intermediate", "fragmented"]:
            cb, cs, auc, iso = run(cfg, scen, form, n_rep)
            rows.append(dict(beta_form=form, scenario=scen,
                             corr_b_beta=cb, corr_b_s=cs, auc=auc, iso=iso))
    out = pd.DataFrame(rows)
    out.to_csv(TAB / "table_beta_form.csv", index=False)
    print(out.round(3).to_string(index=False))
    print("\nMean convergent corr(b, beta*) by form:")
    for form in ["linear", "multiplicative", "min"]:
        d = out[out.beta_form == form]["corr_b_beta"].mean()
        print(f"  {form:14s}: {d:.3f}")
    return out


if __name__ == "__main__":
    main()
